version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/ucsd-cloud-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u oauth2accesstoken -p $GCR_IO_CREDENTIAL https://gcr.io
            docker tag app "gcr.io/introspect-data/ucsd-cloud-cli:${CIRCLE_SHA1}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag app "gcr.io/introspect-data/ucsd-cloud-cli:latest"
            fi
            docker push gcr.io/introspect-data/ucsd-cloud-cli
